version: "3.4"
services:
  api-gateway:
    env_file:
      - environment/api-gateway.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.apigateway
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbit
  sender-simulator:
    env_file:
      - environment/sender-simulator.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.data-sender-simulator
  river-management:
    env_file:
      - environment/river-management.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.river-management
    ports:
      - "5001:5000"
      - "8080:8080"
    depends_on:
      - db
  accounts:
    env_file:
      - environment/accounts.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.accounts
    depends_on:
      - db
  telemetry:
    env_file:
      - environment/telemetry.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.telemetry
    depends_on:
      - influxdb
      - rabbit
      - river-management
  reporting:
    env_file:
      - environment/reporting.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.reporting
    depends_on:
      - influxdb
  db:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbit-data:/var/lib/rabbitmq/
        - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - 8086:8086
    volumes:
      # - ./influx-data:/root/.influxdbv2
      - ./influx-data:/var/lib/influxdb2
    
