version: "3.4"
services:
  api-gateway:
    container_name: api-gateway
    env_file:
      - environment/api-gateway.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.apigateway
      target: production
    ports:
      - "5000:5000"
      - "2345:2345" # Debugging port
    volumes: # For debugging
      - ./app/cmd/api-gateway/:/go/src/github.com/flussrd/fluss-back/app/cmd/api-gateway/
      - ./app/api-gateway/:/go/src/github.com/flussrd/fluss-back/app/api-gateway/
    security_opt: # Because the debugger starts up the app and uses process forking to run the app, and this is not allowed
      - seccomp:unconfined
    depends_on:
      - db
      - rabbit
  sender-simulator:
    env_file:
      - environment/sender-simulator.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.data-sender-simulator
  river-management:
    env_file:
      - environment/river-management.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.river-management
    ports:
      - "5001:5000"
      - "8080:8080"
    depends_on:
      - db
  accounts:
    env_file:
      - environment/accounts.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.accounts
    depends_on:
      - db
    ports:
      - "5003:5000"
  telemetry:
    ports:
      - "5002:5000"
    env_file:
      - environment/telemetry.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.telemetry
    depends_on:
      - influxdb
      - rabbit
      - river-management
  reporting:
    env_file:
      - environment/reporting.local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.reporting
    depends_on:
      - influxdb
  db:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27018:27017
  rabbit:
    build:
      context: .
      dockerfile: docker/Dockerfile.rabbit
    ports:
        - 5673:5672
        - 15673:15672
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
      - RABBITMQ_DEFAULT_USER=fluss-service
      - RABBITMQ_DEFAULT_PASS=flusspassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
        - ./rabbit-data:/var/lib/rabbitmq/
        - ./rabbit/definitions.json:/tmp/rabbit.definitions.json
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - 8086:8086
    volumes:
      # - ./influx-data:/root/.influxdbv2
      - ./influx-data:/var/lib/influxdb2
    
