FROM golang:1.16-alpine
ENV APP_HOME go/src/github.com/flurssrd/fluss-back

RUN mkdir -p $APP_HOME
ADD . $APP_HOME
RUN mkdir build
WORKDIR $APP_HOME

# RUN go mod download
RUN go build -o build/main ./app/cmd/data-sender-simulator/main.go

RUN chmod +x ./build/main

CMD ["./build/main"]