FROM golang:1.16
ENV APP_HOME go/src/github.com/flurssrd/fluss-back

RUN mkdir -p $APP_HOME
ADD . $APP_HOME
WORKDIR $APP_HOME

RUN ls

# RUN go mod download
RUN go build -o main ./app/cmd/accounts/main.go

RUN chmod +x ./main

CMD ["./main"]